### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by techscientist** [Commit451/ForegroundViews#1]
What is the difference between this and a Frame Layout? What can we use it for? What is its purpose - what does it do?

Awaiting your reply... Nice library, btw

**Comment by Jawnnypoo** [comment]
Hey there! So this provides the same foreground functionality as FrameLayout does for different ViewGroups, such as LinearLayout and RelativeLayout, since it is not supported in either of those view groups. That is pretty much all it does. Its a simple library, but I thought it would be useful for others!

**Comment by sirvon** [comment]
Alot of us understand in implementation the advantages of using FrameLayout, things like fragments and such but maybe the actually theory and understanding behind exactly what is going on...has been lost on us.

Can you, if you don't mind explaining or pointing us in the right direction in explaining what the foreground functionality really is.....?

thanks! for your time and the library!
